CREATE TABLE timesheet
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    hours_worked DOUBLE PRECISION NOT NULL,
    employee_id BIGINT NOT NULL,
    CONSTRAINT pk_timesheet PRIMARY KEY (id),
    CONSTRAINT fk_timesheet_on_employee FOREIGN KEY (employee_id) REFERENCES employee (id)
);